service: tradingbot
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  region: sa-east-1

functions:
  producer:
    layers:
        - Ref: PythonRequirementsLambdaLayer
    handler: handler.trade
    events:
      - sns: 
          arn: arn:aws:sns:us-west-2:977566059069:buy
          topicName: buy

    environment:
      WALLET_ADDRESS: "0xD3d991067E60B458068b1767295ffBc6A23EC7cc"
      SECRET: "4Z5fqQvwMduo6TzkBuf1fSTG5WIrfL2FtvOYyEKX"
      KEY: "5ad00553-c5b7-0df5-e654-1cd5fd7b733d"
      PASSPHRASE: "Iq_a1etkD6G7t8zQK6Ug"
      LEGACY_SIGNING: "False"
      WALLET_TYPE: "METAMASK"
      STARK_PRIVATE_KEY: "053b26b0d600c4f2bdc3ffa4616e105977fe3941ad6a7a5d8c894dc510cc5b8a"
      MAINNET: "False"

plugins:
  - serverless-lift
  - serverless-python-requirements
package:
  patterns:
    - '!node_modules/**'

custom:
  pythonRequirements:
    # slim: true
    # dockerPip: true
    layer: true